# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}"}

ruby '2.4.3'

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pg'
gem 'rake'
gem 'puma'
gem 'foreman'
gem 'json'
gem 'rest-client'

group :development do
  gem 'tux'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
end